Reddit shortener
hlmtre/pybot pull request #5
Opened 2020-01-07 04:45 UTC by MechMaster48

rshort module properly grabbing information and posting to IRC as well as the modified link in the description. This was done by creating a reddit_link method in the Shortener class and calling it from rshort. The shortener module will also not be triggered by reddit links anymore since that will be handled by rshort to place in the link description. Date and time of reddit post has also been added to description as well. First pull request on github, hope this worked out ok.

2020-01-10 17:04 UTC, hlmtre requested changes
Looks pretty good but I'd like to verify it behaves like I think: shorten either way, but if it's a reddit link, also print reddit info.

Definitely also change to fail fast too.

2020-01-10 17:04 UTC, hlmtre commented on modules/rshort.py
> +      sub_time = datetime.utcfromtimestamp(sub.created).strftime('%Y/%m/%d--%H:%M') # converts from POSIX timestamp to human readable
```suggestion
      sub_time = datetime.utcfromtimestamp(sub.created).strftime('%Y/%m/%d@%H:%M') # converts from POSIX timestamp to human readable
```

2020-01-10 17:04 UTC, hlmtre commented on modules/rshort.py
> +if successful_import is True:
```suggestion
if not successful_import:
  print("couldn't import praw or praw.ini not completed!")
  return
  
# unindent the rest of the file; we'd return from it first instead if we can't move on
```

2020-01-10 21:33 UTC, MechMaster48 commented
Will add these changes in along with the other changes I am making after doing some research. Thanks for the feedback.

2020-01-16 00:45 UTC, hlmtre approved these changes

2020-01-16 00:45 UTC, merged